### ISSUE TITLE
не удается запустить службу

### ISSUE THREAD

**Issue by evgeny-sv** [LazarenkoA/prometheus_1C_exporter#24]
файл настроек:
Explorers:
  - Name: ClientLic
    Property:
      timerNotyfy: 60
  - Name: AvailablePerformance
    Property:
      timerNotyfy: 10
  - Name: CPU
    Property:
      timerNotyfy: 10
  - Name: disk
    Property:
      timerNotyfy: 10
  - Name: SheduleJob
    Property:
      timerNotyfy: 10
  - Name: Session
    Property:
      timerNotyfy: 60
  - Name: Connect
    Property:
      timerNotyfy: 60
  - Name: SessionsData
    Property:
      timerNotyfy: 10
  - Name: ProcData
    Property:
      processes:
        - rphost
        - ragent
        - rmngr
      timerNotyfy: 10

# http сервис который возвращает массив json с кредами к БД
# нужно для метрики SheduleJob
# пример json:
#[
#  {
#    "Name": "hrmcorp-n17",
#    "UserName": "",
#    "UserPass": ""
#  }
#]

RAC:
  Path: "C:\Program Files\1cv8\8.3.22.1923\bin\rac.exe"
  Port: "1545"      # Не обязательный параметр
  Host: "localhost" # Не обязательный параметр
  Login: ""         # Не обязательный параметр
  Pass: ""          # Не обязательный параметр

LogDir:                       # Если на задан логи будут писаться в каталог с исполняемым файлом
LogLevel: 5                   # Уровень логирования от 2 до 6, где 2 - ошибка, 3 - предупреждение, 4 - информация, 5 - дебаг, 6 - трейс
TimeRotate: 1                 # Время в часах через которое будет создаваться новый файл логов
TTLLogs: 8                    # Время жизни логов в часах

///////////
C:\Program Files\1c_exporter>1c_exporter.exe --settings=C:\Program Files\1c_exporter\settings.yaml
panic: Файл настроек "C:\\Program" не найден

goroutine 1 [running]:
main.loadSettings(0xc00001a36b, 0xa, 0x2)
        /home/runner/work/prometheus_1C_exporter/prometheus_1C_exporter/settings.go:75 +0x3cc
main.main()
        /home/runner/work/prometheus_1C_exporter/prometheus_1C_exporter/main.go:49 +0x29b

**Comment by LazarenkoA** [comment]
путь к settings возьми в двойные кавычки

**Comment by evgeny-sv** [comment]
так тоже пробовал

C:\Program Files\1c_exporter>1c_exporter.exe --settings="C:\Program Files\1c_exporter\settings.yaml"
panic: Файл настроек "C:\\Program Files\\1c_exporter\\settings.yaml" не найден

goroutine 1 [running]:
main.loadSettings(0xc00001c1cb, 0x2a, 0x1)
        /home/runner/work/prometheus_1C_exporter/prometheus_1C_exporter/settings.go:75 +0x3cc
main.main()
        /home/runner/work/prometheus_1C_exporter/prometheus_1C_exporter/main.go:49 +0x29b

**Comment by LazarenkoA** [comment]
значит файла нет по данному пути

**Comment by LazarenkoA** [comment]
я могу закрыть это обращение?

**Comment by evgeny-sv** [comment]
да. разобрался. спасибо
