### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by phant** [LazarenkoA/prometheus_1C_exporter#30]
```
июн 26 22:03:22 srv1c systemd[1]: Started Prometheus 1C exporter.
июн 26 22:03:22 srv1c 1c_exporter[3582990]: port : 9091
июн 27 22:00:22 srv1c 1c_exporter[3582990]: panic: runtime error: invalid memory address or nil pointer dereference
июн 27 22:00:22 srv1c 1c_exporter[3582990]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x751899]
июн 27 22:00:22 srv1c 1c_exporter[3582990]: goroutine 38 [running]:
июн 27 22:00:22 srv1c 1c_exporter[3582990]: github.com/LazarenkoA/LogrusRotate.(*watcher).Cancel(0x0)
июн 27 22:00:22 srv1c 1c_exporter[3582990]:         /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:99 +0x19
июн 27 22:00:22 srv1c 1c_exporter[3582990]: github.com/LazarenkoA/LogrusRotate.(*Rotate).DeleteEmptyFile(0xc0001e4bd0, 0xc000012120)
июн 27 22:00:22 srv1c 1c_exporter[3582990]:         /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:287 +0x47a
июн 27 22:00:22 srv1c 1c_exporter[3582990]: github.com/LazarenkoA/LogrusRotate.(*Rotate).Start.func2.1({0xc00012c2e0, 0x1f}, {0xa3c770, 0xc000113a00}, {0x100?, 0xffffffffffffff9c?})
июн 27 22:00:22 srv1c 1c_exporter[3582990]:         /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:219 +0xa5
июн 27 22:00:22 srv1c 1c_exporter[3582990]: path/filepath.walk({0xc00012c2e0, 0x1f}, {0xa3c770, 0xc000113a00}, 0xc000229fb0)
июн 27 22:00:22 srv1c 1c_exporter[3582990]:         /opt/hostedtoolcache/go/1.19.9/x64/src/path/filepath/path.go:438 +0xba
июн 27 22:00:22 srv1c 1c_exporter[3582990]: path/filepath.walk({0xc00013e3c0, 0x14}, {0xa3c770, 0xc00030c1a0}, 0xc000229fb0)
июн 27 22:00:22 srv1c 1c_exporter[3582990]:         /opt/hostedtoolcache/go/1.19.9/x64/src/path/filepath/path.go:458 +0x285
июн 27 22:00:22 srv1c 1c_exporter[3582990]: path/filepath.Walk({0xc00013e3c0, 0x14}, 0xc0015affb0)
июн 27 22:00:22 srv1c 1c_exporter[3582990]:         /opt/hostedtoolcache/go/1.19.9/x64/src/path/filepath/path.go:521 +0x6c
июн 27 22:00:22 srv1c 1c_exporter[3582990]: github.com/LazarenkoA/LogrusRotate.(*Rotate).Start.func2()
июн 27 22:00:22 srv1c 1c_exporter[3582990]:         /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:208 +0xba
июн 27 22:00:22 srv1c 1c_exporter[3582990]: created by github.com/LazarenkoA/LogrusRotate.(*Rotate).Start
июн 27 22:00:22 srv1c 1c_exporter[3582990]:         /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:206 +0x445
июн 27 22:00:22 srv1c systemd[1]: 1c_exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
июн 27 22:00:22 srv1c systemd[1]: 1c_exporter.service: Failed with result 'exit-code'.
июн 27 22:00:22 srv1c systemd[1]: 1c_exporter.service: Consumed 23h 21min 51.635s CPU time.
```

Возможно это связано с тем, что днем (июн 27) служба сервера 1с сожрала всю память сервера и её прибил OOM-killer.

В качестве костыля добавил с Unit сервиса рестарт
```
Restart=always
RestartSec=30s
```

**Comment by LazarenkoA** [comment]
Это исправилено
https://github.com/LazarenkoA/prometheus_1C_exporter/issues/29
