### ISSUE TITLE
Процесс экспортера завершается с ошибкой

### ISSUE THREAD

**Issue by Totoshka1001** [LazarenkoA/prometheus_1C_exporter#33]
После совсем непродолжительной работы, процесс экспортера завершается ошибкой
Используется последний релиз

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x751899]

goroutine 36 [running]:
github.com/LazarenkoA/LogrusRotate.(*watcher).Cancel(0x0)
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:99 +0x19
github.com/LazarenkoA/LogrusRotate.(*Rotate).DeleteEmptyFile(0xc00021a810, 0xc0002149c8)
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:287 +0x47a
github.com/LazarenkoA/LogrusRotate.(*Rotate).Start.func2.1({0xc000028aa0, 0x20}, {0xa3c770, 0xc0003a8d00}, {0x100?, 0xffffffffffffff9c?})
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:219 +0xa5
path/filepath.walk({0xc000028aa0, 0x20}, {0xa3c770, 0xc0003a8d00}, 0xc000105fb0)
        /opt/hostedtoolcache/go/1.19.9/x64/src/path/filepath/path.go:438 +0xba
path/filepath.walk({0xc000249278, 0x15}, {0xa3c770, 0xc0003a8a90}, 0xc000105fb0)
        /opt/hostedtoolcache/go/1.19.9/x64/src/path/filepath/path.go:458 +0x285
path/filepath.Walk({0xc000249278, 0x15}, 0xc000105fb0)
        /opt/hostedtoolcache/go/1.19.9/x64/src/path/filepath/path.go:521 +0x6c
github.com/LazarenkoA/LogrusRotate.(*Rotate).Start.func2()
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:208 +0xba
created by github.com/LazarenkoA/LogrusRotate.(*Rotate).Start
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:206 +0x445
```

**Comment by Totoshka1001** [comment]
А регулярное обновление релиза планируется? Или новые изменения получать только из кода, ручной сборкой?

**Comment by LazarenkoA** [comment]
вчера собрал новый релиз, хотел поднакопить изменений перед выпуском
